<main class="bd-masthead code-in-the-dark" id="content" role="main">
    <?php echo $this->render('layout/partial/fork-me-on-github-ribbon'); ?>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-12 mx-auto my-5">
                <h1 class="mb-3 text-light text-center text-shadow">Credits</h1>
            </div>
        </div>
    </div>
    <div class="cover-scrollspy"><i class="fas fa-chevron-down"></i></div>
</main>
<div class="masthead-followup row m-0 border border-white">
    <div class="col-12 col-md-12 p-5 bg-light border border-white">
        <div class="container">
            <p class="lead">
                Throughout my years of programming, before I created JiNexus Framework, I've been using various kinds of PHP frameworks and open-source projects—even
                up to this day. I acknowledge those technologies for helping me throughout the time and molding me into the developer I am today, giving me a depth
                of understanding of S.O.L.I.D. principles and various Design Patterns. Below is a short list of the projects that inspired JiNexus Framework.
            </p>
            <ul>
                <li class="lead mb-2">
                    <a href="https://getlaminas.org/" target="_blank">Laminas & Mezzio</a> — Not all but most of JiNexus Framework components are based or highly influenced by Laminas.
                </li>
                <li class="lead mb-2">
                    <a href="https://designpatternsphp.readthedocs.io/en/latest/" target="_blank">DesignPatternsPHP</a> — JiNexus Framework referenced the best practices
                    and design pattern from DesignPatternsPHP.
                </li>
                <li class="lead mb-2">
                    <a href="https://scotch.io/bar-talk/s-o-l-i-d-the-first-five-principles-of-object-oriented-design" target="_blank">S.O.L.I.D Principles</a>
                    — JiNexus Framework aims to come easily be extended, modified, tested, and refactored without any problems by adhering to the guidelines
                    of S.O.L.I.D Principles.
                </li>
                <li class="lead mb-2">
                    <a href="https://www.php-fig.org/psr/" target="_blank">PHP Standards Recommendations</a> — JiNexus Framework referenced a standardization approach for PHP from PSR.
                </li>
                <li class="lead mb-2">
                    <a href="https://getbootstrap.com" target="_blank">Bootstrap 4</a> — JiNexus Framework website is currently using the Bootstrap 4 docs.css theme.
                    I did some research if I am allowed to use their docs.css in my open-source or commercial projects and since docs.css is considered being part
                    of the Bootstrap package and falls under the same license as the rest of the framework. Yes! They allow it to be used, you may check their conversation
                    in this <a href="https://github.com/twbs/bootstrap/issues/7280" target="_blank">thread</a>.
                </li>
            </ul>
            <p class="lead">Thank you, open source.</p>
        </div>
    </div>
</div>
